project:
  name: aws-quickstart-cribl-logstream
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
    - us-west-2
  parameters: 
    webAccessCidr: 0.0.0.0/0
    QSS3KeyPrefix: logstream/
    QSS3BucketRegion: us-west-2
    QSS3BucketName: 'aws-quickstart-cribl-logstream'
tests:
  cribl-deploy-new-vpc-arm:
    template: templates/cribl-single-arm64.entrypoint.template.yaml

